### ISSUE TITLE
中文文件下載后，不能打開，例如pdf

### ISSUE THREAD

**Issue by oliguo** [Coolerfall/Android-HttpDownloadManager#1]
下載含有中文pdf文件，會無法打開或損壞，但將文件改回英文名文件重新下載，能正常打開，
是不是下載時，需要在哪裡進行編碼？求指教

**Comment by Coolerfall** [comment]
能否给一个下载链接我试试？ Android developer, Gopher, Open Source, Charcoal Drawing 在2015年05月07日 17:07 ，oliverguo写道： 下載含有中文pdf文件，會無法打開或損壞，但將文件改回英文名文件重新下載，能正常打開， 是不是下載時，需要在哪裡進行編碼？求指教 — Reply to this email directly or view it on GitHub.

**Comment by oliguo** [comment]
我剛發郵件給你，有勞你測試下，謝謝

**Comment by oliguo** [comment]
我發現再用url編碼，下載失敗，




if (mDownloadManager.isDownloading(downloadId)) {
			mDownloadManager.cancel(downloadId);
		} else {
			String urls=URL[downloadId];
			String urlFront=urls.substring(0,urls.lastIndexOf(File.separator));
			String urlFile=urls.substring(urls.lastIndexOf(File.separator));
			String urlFileName=urlFile.substring(0,urlFile.lastIndexOf(".pdf"));
			String urlNAME="";
			try {
				urlNAME=URLEncoder.encode(urlFileName, "GBK");
				Log.d("URLENCODEPDF",urlFront+File.separator+urlNAME +".pdf");

				DownloadRequest request = new DownloadRequest()
						.setDownloadId(downloadId)
						.setDownloadListener(new Listener())
						.setRetryTime(5)
						.setAllowedNetworkTypes(this,0)//original:(this, DownloadRequest.NETWORK_WIFI)
						.setUrl(urlFront+File.separator+urlNAME+".pdf");
				mDownloadManager.add(request);
			} catch (UnsupportedEncodingException e) {
				e.printStackTrace();
			}

		}

**Comment by Coolerfall** [comment]
请尝试一下在DownloadRequest中使用setDestinationPath(destPath)来设置目标下载路径

**Comment by oliguo** [comment]
在 new DownloadRequest()后加上setDestinationPath("/sdcard/"),還是不行，最後還是把php 調回的url改回url編碼，能下載成功，不過url有中文應該很少出現，多數都轉變為url編碼

**Comment by Coolerfall** [comment]
一般来说极少遇到这种情况，我会尝试下解决这个问题

**Comment by oliguo** [comment]
謝謝

**Comment by oliguo** [comment]
最後，我在

/** get the default download file path */
	private String getDefaultFilePath() {
		String filename = mUrl.substring(mUrl.lastIndexOf(File.separator));
		String temp1="";
		try {
			temp1= URLDecoder.decode(filename,"UTF-8");
		} catch (UnsupportedEncodingException e) {
			e.printStackTrace();
		}

		if (TextUtils.isEmpty(filename)) {
			filename = mTimestamp + ".down";
		}
		if(!temp1.equals(filename)){
			filename=temp1;
		}

		return DEFAULT_DIR + File.separator + filename;
	}

**Comment by Coolerfall** [comment]
可以使用setDestinationPath("/sdcard/download/文本.txt")，这种方式来设置最终下载后的文件的名称（你之前设置的方式错了，这个不是用来设置下载目录的，而是最终文件的绝对路径），如果不设置才会去生成一个默认的文件名，不过感谢您的建议

**Comment by oliguo** [comment]
明白，謝謝
