### ISSUE TITLE
allow custom HttpURLConnection instances

### ISSUE THREAD

**Issue by eighthave** [Coolerfall/Android-HttpDownloadManager#4]
This looks like a great library!  It would be the perfect thing for my needs if I could override the creation of the `HttpURLConnection` instances.  For example, to set the proxy settings, or to force using `HttpsURLConnection` to make sure only https:// connections are ever made.  I think the easiest way to implement this would be to add a method to `DownloadManager` that was responsible for generating the instance, and the default code could be overridden by registering a callback in `DownloadManager`.  Something like this:

```java
public interface DownloadMethod {
   public HttpURLConnection getHttpURLConnection(URL url);
}

public class DownloadManager {
  private DownloadMethod downloadMethod;
  public void registerDownloadMethod(DownloadMethod method) {
    downloadMethod = method;
  }

  public HttpURLConnection getHttpURLConnection(URL url) {
    if (downloadMethod == null) {
      return (HttpURLConnection) url.openConnection();
    } else {
      return downloadMethod.getHttpURLConnection(url);
    }
  }
}

```

**Comment by Coolerfall** [comment]
Thanks for your suggestion, but I just want to keep it easy to use for now. Maybe this will be added in later.

**Comment by eighthave** [comment]
I totally agree it should be kept easy.  The approach I describe means
that the default setup remains exactly the same.  The developer using
the library would not have to do anything different.  It would only be
an optional override.

**Comment by Coolerfall** [comment]
I got it. But one HttpURLConnection corresponds to one downloading, it seems that this should be added in DownloadRequest.

**Comment by eighthave** [comment]
Since it is the HttpURLConnection instance that needs to be changed, I
don't understand how that could happen in DownloadRequest, since it does
not do anything with HttpURLConnection instances.  For the use cases I
have in mind, things like disabling insecure HTTPS options or adding
support for a proxy, those would happen globally in the app, not per
request.

**Comment by Coolerfall** [comment]
If only one HttpURLConnection, let's image that there were 2 or more requests is in downloading, they should not use the same HttpURLConnection.

**Comment by eighthave** [comment]
Yes, that makes sense.  But what I propose does not change that either
way.  It just changes the method of getting an HttpURLConnection
instance from a URL instance.  What I propose does not make all calls to
getHttpURLConnection(URL url) return the same instance.

**Comment by Coolerfall** [comment]
I open URL in DownloadDispatcher for each DownloadRequest, so I think we should add method in DownloadRequest to set custom HttpURLConnection. Then DownloadDispatcher can get HttpURLConnection if existed, otherwise open a new HttpURLConnection .

**Comment by eighthave** [comment]
Sounds fine, but I'm missing the connection between that idea and this merge request, since this request doesn't change the instantiation behavior, just customizes the instance when created.
