### ISSUE TITLE
How can I fix Authentication from server?

### ISSUE THREAD

**Issue by aaronat1** [Coolerfall/Android-HttpDownloadManager#44]
Hi, 
There is any way to fix user and pass credentials for downloading files from server?

Regards

**Comment by Coolerfall** [comment]
You can implement your own Downloader.

**Comment by aaronat1** [comment]
Thanks Vincent,

can you give an example to create a Downloader and use in your library
please?

Regards

2016-08-04 16:30 GMT+01:00 Vincent Cheung <notifications@github.com>:

**Comment by aaronat1** [comment]
I want to use OkHtt but do not get fix user and pass to authenticate with
the server

Regards

2016-08-04 16:34 GMT+01:00 Aaron Asencio <aaron.asencio.tavio@gmail.com>:

**Comment by Coolerfall** [comment]
You can refer to OkHttpDownloader.
