### ISSUE TITLE
Broken link causes a leak

### ISSUE THREAD

**Issue by duduBaiao** [Coolerfall/Android-HttpDownloadManager#50]
Hi,

It seems that if the url is broken the connection leaks.

When that happens I see a message like this on the console:

> W/OkHttp: A connection to http://feeds-tmp.soundcloud.com/ was leaked. Did you forget to close a response body?

**Comment by Coolerfall** [comment]
Which version did you test on? I have tested this url, but I didn't meet this error.

**Comment by duduBaiao** [comment]
Thanks for answering @Coolerfall.

I'm using the last master commit.

You can test on any invalid/broken url. The url showed above is not complete. Please try this one:

http://podcast.canaltech.com.br/1735x.mp3

You'll see something like this on the log:

> W/OkHttp  (25435): A connection to http://podcast.canaltech.com.br/ was leaked. Did you forget to close a response body?

**Comment by Coolerfall** [comment]
I still didn't get this message, just get 404 error however.

**Comment by duduBaiao** [comment]
Yeah. That's right. This happens to me too.

But my app tries to download the same file several times, after a short delay. Can you please test that situation?

**Comment by Coolerfall** [comment]
1.Try to download serveral times, with different DownloadRequest or same DownloadRequest?
2.After a short delay, what does this mean?

**Comment by duduBaiao** [comment]
1 - With different instances of "DownloadRequest".
2 - 15 seconds

**Comment by Coolerfall** [comment]
Ok, I got this message. I'v changed some code, and I didn't get this message anymore. U can checkout on develop branch.

**Comment by duduBaiao** [comment]
Thanks @Coolerfall.

I'll test it in the next days. ;)
