### ISSUE TITLE
Unique Download Ids.

### ISSUE THREAD

**Issue by itabdullah1** [Coolerfall/Android-HttpDownloadManager#54]
I have implemented this library to download files from the list of items displayed to the user in a view pager. Each item of the view pager can be downloaded. If for example, the user is downloading a file which has a download Id "1" and he comes out of the app while the download goes in the background. Again the user enters the app and now starts download of another file. This time too the new file is given download Id as "1". Due to this, I am unable to display progress of the download to the users because both the downloads have the same Id.
Everytime the user enters the app, I setup download manager as below.

**Is there a way to have a unique id for each download even after exiting and re-entering the app?**

    private void setupDownload() {
        OkHttpClient client = new OkHttpClient.Builder().build();
        downloadManager =
                new DownloadManager.Builder().context(this)
                        .downloader(OkHttpDownloader.create(client))
                        .threadPoolSize(1)
                        .logger(new Logger() {
                            @Override
                            public void log(String message) {
                                Log.d(TAG, "Log message: " + message);
                            }
                        })
                        .build();
    }

DownloadRequest request = new DownloadRequest.Builder()
                    .url(uriString)
                    .retryTime(0)
//                    .retryInterval(2, TimeUnit.SECONDS)
//                    .progressInterval(1, TimeUnit.SECONDS)
                    .priority(Priority.NORMAL)
                    .allowedNetworkTypes(DownloadRequest.NETWORK_WIFI | DownloadRequest.NETWORK_MOBILE)
                    .destinationFilePath(destPath)
                    .downloadCallback(new DownloadCallback() {

                        @Override
                        public void onStart(int downloadId, long totalBytes) {
.....

**Comment by Coolerfall** [comment]
You can download file in service.

**Comment by itabdullah1** [comment]
Thanks for the quick response. I will implement the downloading part in a service.

**Comment by Coolerfall** [comment]
Not now, maybe later.
