### ISSUE TITLE
Pause Download

### ISSUE THREAD

**Issue by cshalysongoncalves** [Coolerfall/Android-HttpDownloadManager#56]
How do I pause a download?

**Comment by Coolerfall** [comment]
Use DownloadManger.cancel(int downloadId);

**Comment by cshalysongoncalves** [comment]
There is no summary of a download from a state that had been paused right?

**Comment by Coolerfall** [comment]
No . If you use DownloadManger.cancel(int downloadId), the download will stop immediately.

**Comment by cshalysongoncalves** [comment]
Thanks!
