### ISSUE TITLE
Download not cancelled

### ISSUE THREAD

**Issue by mraj0045** [Coolerfall/Android-HttpDownloadManager#63]
The download is not canceling when used inside FirebaseJobDispatcher.
When canceling the job manually, the download still continues even after the job canceled.

And also tried to cancel the download from the code manually. But cancel download only works if the same "object" created for downloading the file is used for canceling. If I create a new DownloadManager Object and cancel the download, it should cancel.

**Comment by Coolerfall** [comment]
You should create a global DownloadManager, and then you can cancel task.

**Comment by mraj0045** [comment]
What if I close the app and open again? will the global DownloadManager work?

**Comment by Coolerfall** [comment]
What do you mean close the app？

**Comment by mraj0045** [comment]
while downloading some file I'm closing the app. The download happens in the background. if I open the app again and try to cancel the download, will it work?

**Comment by Coolerfall** [comment]
Do you mean you have a service in background? If so, the gloabl DownloadManager will work.

**Comment by mraj0045** [comment]
yes

**Comment by Coolerfall** [comment]
You should create an instance of DownloadManager in your service, so that you can control the downloading.

**Comment by mraj0045** [comment]
What I want to do is that there is a separate page for Managing downloads. There I can pause, resume, cancel the download. But download happens in a separate service. Even if create an instance Of DownloadManager in service, how will I able to perform (pause, resume, cancel) from the activity.

**Comment by Coolerfall** [comment]
I think you should check communication between activity and service on google.
