### ISSUE TITLE
Bind DownloadManager to system broadcast

### ISSUE THREAD

**Issue by maxi182Eman** [Coolerfall/Android-HttpDownloadManager#66]
Hi, I am needing to bind your DownloadManager to a system brodcast, so onRecive should be called when the download is complete, how can I achive this?

thanks

**Comment by Coolerfall** [comment]
So in which case you want to send a brodcast? Just in your app?

**Comment by maxi182Eman** [comment]
Hi, Yes, when the dowload is complete, and the app is not in the foreground, onRecive method should be called and able to grab the downloadReferenceId.
Thanks

**Comment by Coolerfall** [comment]
Just use `sendBroadcast` in onComplete.

**Comment by maxi182Eman** [comment]
Hi, but does your Oncomplete method will be called when the download is complete while the app is close?

**Comment by Coolerfall** [comment]
You should handle this in service by yourself. If you want to know how to keep app keeps alive in background, you should check Android's tutorial.
