### ISSUE TITLE
open failed: EPERM (Operation not permitted) android 11

### ISSUE THREAD

**Issue by sanketkoladiya** [coolerfall/Android-HttpDownloadManager#81]
When I am trying to download a file from server it's giving me the error like **open failed: EPERM (Operation not permitted)**

I want to write a file inside music/AppNameFolder

File I want to write : /storage/emulated/0/Music/Demo/Panghat (SongsMp3.fm)20210810185325.wav

**Comment by sanketkoladiya** [comment]
@coolerfall  @tian9246 can you please help me out with this issue?

**Comment by coolerfall** [comment]
You should add storage permission check.

**Comment by coolerfall** [comment]
It seems that this is caused by SAF after android 10. Add `android:requestLegacyExternalStorage` in `manifest` to solve this problem temporarily..
