### ISSUE TITLE
Set relative destination file path

### ISSUE THREAD

**Issue by tosam144** [coolerfall/Android-HttpDownloadManager#97]
Is it possible to use my own relative path to store downloads to? I want to save downloads to `context.filesDir`. I tried to use `.relativeFilepath(context.filesDir.absolutePath)` but it always falls back to a subdirectly of `Downloads`. Is there a way to set my own path not under `Downloads`?

**Comment by coolerfall** [comment]
Currently not support. You can move the file after completed.
