### ISSUE TITLE
下载的文件名错误

### ISSUE THREAD

**Issue by andzhangs** [coolerfall/Android-HttpDownloadManager#99]
1、有时会出现文件名的后缀为：.down 
2、有时会出现文件名格式：“正确文件名”;filename*=utf-8''正确文件名
3、有时会出现文件名格式：“文件名(注：不带后缀)”;filename*=utf-8''文件名(注：不带后缀)

**Comment by andzhangs** [comment]
目前处理方式是：下载成功后，自动替换掉成 正确文件名。

**Comment by andzhangs** [comment]
目前处理方式是：下载成功后，重命名。

**Comment by coolerfall** [comment]
后续将会处理
